title: ArmsWay
description: Disposable Blood Pressure Cuff Sleeves
url: "https://armsway.com"
baseurl: "" # Leave blank for the root domain
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge